module hospitales {

    interface hospital{
        boolean insertarHospital(in long codigoHospital, in wstring nombre, in wstring direccion, in wstring telefono, in char estado);
        boolean actualizarHospital(in long codigoHospital, in wstring nombre, in wstring direccion, in wstring telefono, in char estado);
        boolean eliminarHospital(in long codigoHospital);
        wstring consultarHospital(in long codigoHospital);

        oneway void shoutdown();

    };
};

