package IDL.hospitales;

/**
* hospitales/hospitalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hospital.idl
* s�bado 10 de noviembre de 2018 06:30:26 PM COT
*/

public final class hospitalHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL.hospitales.hospital value = null;

  public hospitalHolder ()
  {
  }

  public hospitalHolder (IDL.hospitales.hospital initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL.hospitales.hospitalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL.hospitales.hospitalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL.hospitales.hospitalHelper.type ();
  }

}
